### ISSUE TITLE
CMake Path issue

### ISSUE THREAD

**Issue by NarvaniVishal** [sanketnaik99/doctors-prescription#1]
Could not determine the dependencies of task ':sdk:mergeDebugNativeLibs'.
> Gradle project cmake.path is /Users/mac/Downloads/doctors-prescription-master/android/sdk/libcxx_helper/CMakeLists.txt but that file doesn't exist
<img width="1220" alt="Screenshot 2022-08-09 at 11 20 50 PM" src="https://user-images.githubusercontent.com/48939792/183724598-453c0d50-e341-43c4-8d7d-5d98d255e89b.png">

**Comment by sanketnaik99** [comment]
@NarvaniVishal This is probably related to OpenCV. Make sure that you are importing the OpenCV SDK for android before building the app.

**Comment by NarvaniVishal** [comment]
Yes, Imported the OpenCV SDK from scratch and issue is fixed now :)
